module.exports = {
    BASE_URL: "https://opendata-download-metfcst.smhi.se/",
    images: [
      require('./assets/0.png'),
      require('./assets/1.png'),
      require('./assets/2.png'),
      require('./assets/3.png'),
      require('./assets/4.png'),
      require('./assets/5.png'),
      require('./assets/6.png'),
      require('./assets/7.png'),
      require('./assets/8.png'),
      require('./assets/9.png'),
      require('./assets/10.png'),
      require('./assets/11.png'),
      require('./assets/12.png'),
      require('./assets/13.png'),
      require('./assets/14.png'),
      require('./assets/15.png'),
      require('./assets/16.png'),
      require('./assets/17.png'),
      require('./assets/18.png'),
      require('./assets/19.png'),
      require('./assets/20.png'),
      require('./assets/21.png'),
      require('./assets/22.png'),
      require('./assets/23.png'),
      require('./assets/24.png'),
      require('./assets/25.png'),
    ]
  };
